# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_c_compilerclangpython2.7
    - CONFIG=osx_c_compilerclangpython3.6
    - CONFIG=osx_c_compilerclangpython3.7
    - CONFIG=osx_c_compilertoolchain_cpython2.7
    - CONFIG=osx_c_compilertoolchain_cpython3.6
    - CONFIG=osx_c_compilertoolchain_cpython3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ZUe8BWL+aMh+gdFSLN3PCb8zkuMY4lN8BFUguG0FLfuMkXxp3hoT9DZbDX22GLRfvy4Cq6Ase3IgyqJ+oCfB9CQ0MMgdDH/vdivYn6P2bbLuEA7hduNExWh4UnD9oGv/xWQkXs3W7uUrGua0IHqqoyx5/+wt6bV5H1jc28EmN/rN9ohcnTn3I9g/J/wdYrXzJ+0wruXkERpnQ071a42kxUkmVxC3plLjEEQKnSqyCgPwkAbpe2nRvriYg86khKSeFOohslVcsp4B20W3eHHgUDLmjEPNr/Sb1Eo/zYBn9vZVCb6rxJaWmg0FQjK5Lb1ddc0UqxKA3A2sZo6uT4QnqErmXlSEEsXv6EPaCpaqMukE6jPXR4iH77E0HPgLP3IWJpfpYaDf28QpCXZar2Gt4jtU8rr5jOYIwhcnbSS/z74DBo/8DF3BLb70vFH1WrWWgDvqUPBhxj3GdbKhXUEPmIwpf5t28n4eluFPxDexdvAbr5mFgvEllXHMgd28sOc07Ssz9NYHeT1Tb3Argw/sFufCwGCf5e4B//eF4BFpRy5RK2GpaZStp9v8GxxRhOrkhslmD/QUItQN+yPUhIVXVjX/oLfguezgNuWWzt+V6vSmawsylZnOFGOJ3xeES3dWPX+GYEcb+yCtEh0mY3JgiUQmSlDfRwnLp1HcGOkW7Tw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml